import sqlite3
from pathlib import Path

# SQLITE3 DATABASE CONNECTION
# check_same_thread=False allows FastAPI async requests to use the same connection
# This is fine for development but not recommended for production

# Create database directory if it doesn't exist
DB_DIR = Path(__file__).resolve().parent.parent / "database"
DB_DIR.mkdir(exist_ok=True)


# ========== CREATE USERS TABLE ==========
# This table stores user login credentials
# - id: Primary key (auto increment)
# - user_id: User-specified ID used for login
# - email: Email address (MUST BE UNIQUE - prevents duplicate registrations)
# - password: User password (stored as plain text - NOT SECURE, use hashing in production)
# - created_at: Timestamp of user registration (auto-generated by SQLite)

conn_user = sqlite3.connect(str(DB_DIR / "user.db"), check_same_thread=False)
cursor_user = conn_user.cursor()

cursor_user.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")
# Commit all table creations to database
conn_user.commit()

# ========== CREATE PATIENTS TABLE ==========
# This table stores patient information and their medical data
# - patient_id: Unique identifier for the patient
# - patient_name: Name of the patient
# - detected_class: Detected disease class (e.g., cancer type)
# - confidence_score: Confidence score of the detection (0-1)
# - symptoms: Symptoms reported by the patient
# - image_path: Path to the uploaded medical image file
# - created_at: Timestamp when the record was created

conn_patients = sqlite3.connect(str(DB_DIR / "patients.db"), check_same_thread=False)
cursor_patients = conn_patients.cursor()

cursor_patients.execute("""
CREATE TABLE IF NOT EXISTS patients (
    patient_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    patient_name TEXT NOT NULL,
    detected_class TEXT,
    confidence_score REAL,
    symptoms TEXT,
    image_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
)
""")
# Commit all table creations to database
conn_patients.commit()

# ========== CREATE FEEDBACK TABLE ==========
# This table stores user feedback
# - id: Primary key (auto increment)
# - userid: User ID who gave the feedback
# - feedback: The feedback text
# - created_at: Timestamp when feedback was submitted (auto-generated)
conn_feedback = sqlite3.connect(str(DB_DIR / "feedback.db"), check_same_thread=False)
cursor_feedback = conn_feedback.cursor()

cursor_feedback.execute("""
CREATE TABLE IF NOT EXISTS feedback (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid TEXT NOT NULL,
    feedback TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")
# Commit all table creations to database
conn_feedback.commit()

# ========== CREATE PREDICTIONS TABLE ==========
# This table stores prediction history for patients
# - id: Primary key (auto increment)
# - patient_id: Reference to the patient
# - predicted_class: The predicted disease class
# - confidence: Confidence score of the prediction (0-1)
# - image_path: Path to the image that was analyzed
# - created_at: Timestamp when prediction was made
conn_predictions = sqlite3.connect(str(DB_DIR / "predictions.db"), check_same_thread=False)
cursor_predictions = conn_predictions.cursor()

cursor_predictions.execute("""
CREATE TABLE IF NOT EXISTS predictions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id TEXT NOT NULL,
    predicted_class TEXT NOT NULL,
    confidence REAL NOT NULL,
    image_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
)
""")

# Committable creations to database
conn_predictions.commit()